version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: claims-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-claims}
      POSTGRES_USER: ${POSTGRES_USER:-claims_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepass}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - claims-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-claims_user} -d ${POSTGRES_DB:-claims}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  db-init:
    build:
      context: ./docker/db-init
      dockerfile: Dockerfile
    container_name: claims-db-init
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-claims}
      POSTGRES_USER: ${POSTGRES_USER:-claims_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepass}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - claims-network
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claims-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker,ingestion,prod,soap}
      DB_USER: ${DB_USER:-claims_user}
      DB_PASSWORD: ${DB_PASSWORD:-securepass}
      DHPO_SOAP_ENDPOINT: ${DHPO_SOAP_ENDPOINT:-https://qa.eclaimlink.ae/dhpo/ValidateTransactions.asmx}
      SOAP_POLL_INTERVAL_MS: ${SOAP_POLL_INTERVAL_MS:-1800000}
      CLAIMS_AME_STORE_PASS: ${CLAIMS_AME_STORE_PASS}
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      JAVA_OPTS: ${JAVA_OPTS:--Xms512m -Xmx2048m -XX:+UseG1GC}
    volumes:
      - ./data/ready:/app/data/ready
      - ./config:/app/config
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - claims-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres-data:
    driver: local

networks:
  claims-network:
    driver: bridge
