spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claims
    username: claims_user
    password: securepass
    hikari:
      maximum-pool-size: 10      # Laptop optimized (8GB RAM, i5)
      minimum-idle: 5
      auto-commit: false
      connection-timeout: 15000
      leak-detection-threshold: 15000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  # (Optional) Flyway: keep disabled during dev unless you want migrations to run locally
  flyway:
    enabled: false

  main:
    allow-bean-definition-overriding: true
  cache:
    type: simple

logging:
  level:
    com.acme.claims: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.ws: WARN

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,threaddump,loggers"
  endpoint:
    health:
      probes:
        enabled: true

# ================== CLAIMS APP ==================
claims:
  metrics:
    batch:
      enabled: true
  ingestion:
    # our logical profile switch that IngestionConfig uses to select Fetcher/Acker beans
    profile: localfs

    # Scheduler cadence (fast for dev)
    scheduler:
      fixedDelayString: "PT10S"          # every 10s
      initialDelayString: "PT0S"

    # Local filesystem fetcher config (only this fetcher is active under 'localfs')
    localfs:
      readyDir: ${CLAIMS_LOCALFS_WATCH:data/ready}
      archiveOkDir: ${CLAIMS_LOCALFS_ARCHIVE:data/archive/done}
      archiveFailDir: ${CLAIMS_LOCALFS_ERROR:data/archive/error}
      
      # Continuous scanning configuration
      continuous-scan:
        enabled: true
        interval-ms: 5000          # Scan every 5 seconds
        pause-sleep-ms: 150        # Sleep time when paused

    # ACK policy (default OFF per requirements)
    ack:
      enabled: false

    # Threading (executor used by orchestrator/pipeline) - Laptop optimized
    executor:
      core-pool-size: 4          # Laptop optimized (8GB RAM, i5)
      max-pool-size: 8           # Laptop optimized
      queue-capacity: 100        # Keep reasonable for laptop
    poll:
      fixedDelayMs: ${INGESTION_POLL_MS:1000}   # Faster polling for laptop testing
    
    # Concurrency settings for laptop
    concurrency:
      parser-workers: 4          # Laptop optimized

  parser:
    allowNonSchemaAttachments: false
    maxAttachmentBytes: 10485760         # 10MB
    failOnXsdError: false


  # ===== Refdata & Bootstrap =====
  refdata:
    auto-insert: true                    # local: insert-on-miss to keep dev smooth - ENABLED for ref_id population
  bootstrap:
    enabled: false                       # DISABLED: Don't read CSV files on startup, only populate ref_id during persist
    csv-path: "classpath:refdata/"       # your CSVs are already under resources/refdata

# Optional simple cache tuning for refdata lookups (if you use Spring Cache)
claims.security.ame:
  enabled: true
  keystore:
    type: "PKCS12"
    path: "file:config/claims.p12"
    alias: "claims-ame"
    passwordEnv: "CLAIMS_AME_STORE_PASS"
  crypto:
    kekRotationAllowed: true
    gcmTagBits: 128
    keyId : claims-ame.v1