spring:
  application:
    name: claims-app
  main:
    allow-bean-definition-overriding: false   # fail fast if a bean is defined twice
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none                          # no schema mutations
    properties:
      hibernate:
        default_schema: claims                # matches DDL
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

# Flyway stays off by default; enable in prod profile
flyway:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,env,configprops

logging:
  level:
    com.acme.claims: DEBUG                     # orchestrator/fetcher/pipeline visibility
    org.springframework.scheduling: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

claims:
  refdata:
    bootstrap:
      enabled: false                           # profiles override
      strict: false
      location: classpath:refdata/
      delimiter: ','
      batch-size: 500
    auto-insert: true                          # profiles override
