spring:
  application:
    name: claims-app
  main:
    allow-bean-definition-overriding: false   # fail fast if a bean is defined twice
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none                          # no schema mutations
    properties:
      hibernate:
        default_schema: claims                # matches DDL
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

# Flyway stays off by default; enable in prod profile
flyway:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,env,configprops

logging:
  level:
    com.acme.claims: INFO                     # orchestrator/fetcher/pipeline visibility
    org.springframework.scheduling: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

claims:
  refdata:
    bootstrap:
      enabled: false                           # profiles override
      strict: false
      location: classpath:refdata/
      delimiter: ','
      batch-size: 500
    auto-insert: true                          # profiles override
  
  security:
    enabled: false                           # Enable security for API endpoints only
    jwt:
      secret: "claims-jwt-secret-key-change-in-production-2025"
      access-token-expiration: PT15M          # 15 minutes
      refresh-token-expiration: P7D           # 7 days
      issuer: "claims-app"
      audience: "claims-users"
    
    multi-tenancy:
      enabled: false                           # Enable for multi-tenant support
      default-facility-code: "DEFAULT"
    
    sso:
      enabled: false                           # Enable for SSO integration
      default-provider: "OAUTH2"
    
    account-lockout:
      max-failed-attempts: 3
      lockout-duration: PT30M                 # 30 minutes (not used - admin unlock only)
      auto-unlock: false                      # Disabled - admin unlock only
    
    default-admin:
      username: "admin"
      password: "admin123"
      email: "admin@claims.local"