# src/main/resources/application.yml (excerpt)
spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16

claims:
  ingestion:
    concurrency:
      parserWorkers: 16
    queue:
      capacity: 1024
    poll:
      fixedDelayMs: 1000
  soap:
    downloadConcurrency: 16
    transport: http
    endpoint: "https://dhpo.eclaimlink.ae/validateTransactions.asmx"
    # SOAP 1.1 default (SOAPAction is set). Keep switch if you ever need 1.2 later.
    soap12: false
    connectTimeoutMs: 15000
    readTimeoutMs: 120000   # longer reads for Download
    retry:
      maxAttempts: 3        # 1 retry total
      backoffMs: 500
    poll:
      fixedDelayMs: 1800000    # 30 min between delta polls per facility
  fetch:
    stageToDisk:
      force: false          # global override
      sizeThresholdBytes: 26214400  # 25 MB → disk
      latencyThresholdMs: 8000      # >8s download → disk
      readyDir: "data/ready"

# env defaults (may be overridden by DB per facility)
#DHPO_DEFAULT_LOGIN: "env-user"
#DHPO_DEFAULT_PWD: "env-pass"

dhpo:
  client:
    getNewEnabled: false
    searchDaysBack: 100
    retriesOnMinus4: 3
    connectTimeoutMs: 6000
    readTimeoutMs: 15000
    downloadTimeoutMs: 120000
    stageToDiskThresholdMb: 25

claims.security.ame:
  enabled: true
  keystore:
    type: "PKCS12"                    # or "PKCS12" or "FILE"
    path: "file:config/claims.p12" # or "file:config/claims.p12" or "file:config/ame.key"
    alias: "claims-ame"
    passwordEnv: "CLAIMS_AME_STORE_PASS"   # only store/pass are env-based
  crypto:
    kekRotationAllowed: true
    gcmTagBits: 128
    keyId : claims-ame.v1 #  used in enc_meta to mark which key encrypted the row
