spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/claims}          # e.g. jdbc:postgresql://db:5432/claims
    username: ${DB_USER:claims_user}
    password: ${DB_PASSWORD:securepass}
    hikari:
      maximum-pool-size: 50      # Increased for 1000-day load
      minimum-idle: 20
      auto-commit: true
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 200
      hibernate.order_inserts: true
      hibernate.order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  main:
    allow-bean-definition-overriding: false
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=20000,expireAfterAccess=30m,recordStats

logging:
  pattern:
    console: "%d{ISO8601} %-5level [%thread] %logger{36} - %msg%n"
  level:
    com.acme.claims: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.ws.client: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,threaddump,env,loggers"
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# ================== CLAIMS APP ==================
claims:
  ingestion:
    # SOAP profile in prod – IngestionConfig ensures only a single fetcher/acker is active
    profile: soap
    mode: soap
    localfs:
      archive-fail-dir: ./data/archive/fail
      archive-ok-dir: ./data/archive/ok

    scheduler:
      fixedDelayString: "PT2M"            # poll every 2 minutes
      initialDelayString: "PT0S"

    # SOAP fetcher / acker config
    soap:
      endpoint: ${DHPO_SOAP_ENDPOINT}     # e.g. https://dhpo.example/soap
      username: ${DHPO_SOAP_USER}
      password: ${DHPO_SOAP_PASSWORD}
      connect-timeout-ms: 10000     # Tolerant for network issues
      read-timeout-ms: 30000

    ack:
      enabled: true                       # best-effort after success (per requirements)

    executor:
      core-pool-size: 16          # Parallel processing
      max-pool-size: 32
      queue-capacity: 5000        # Large buffer for SOAP burst
    
    poll:
      fixedDelayMs: 500           # Faster polling for high volume
    
    concurrency:
      parser-workers: 16          # Parallel XML parsing

  parser:
  monitor:
    kpi:
      enabled: true            # optional KPI summary logs from v_ingestion_kpis (no pipeline changes)
      fixedDelayMs: 120000     # 2 minutes for near-real-time visibility during 30-min poll cycles
    allowNonSchemaAttachments: false
    maxAttachmentBytes: 10485760
    failOnXsdError: false                  # stricter in prod

  # ===== Refdata & Bootstrap =====
  refdata:
    auto-insert: true
    bootstrap:
      enabled: true
      location: "classpath:refdata/"

  security:
    ame:
      enabled: true
      keystore:
        type: "PKCS12"
        path: "file:config/claims.p12"
        alias: "claims-ame"
        passwordEnv: "CLAIMS_AME_STORE_PASS"
      crypto:
        kekRotationAllowed: true
        gcmTagBits: 128
        keyId : claims-ame.v1

  soap:
    endpoint: ${DHPO_SOAP_ENDPOINT}
    soap12: false
    connectTimeoutMs: 5000
    readTimeoutMs: 15000
    retry:
      maxAttempts: 3
      backoffMs: 500
    poll:
      fixedDelayMs: 18000000
    downloadConcurrency: 16
    facilityPoll:
      strategy: "staggered"         # staggered | concurrent (planning knob; current code logs only)
      staggerIntervalMs: 750         # delay between facilities when staggered
      maxConcurrent: 8               # soft target for facility parallelism
      enableAdvanced: false          # IMPORTANT: keep false to preserve current behavior
  metrics:
    facilityQueueEnabled: true       # when true, emits facility queue metrics from fetch coordinator

  fetch:
    stageToDisk:
      force: false          # Don't force all files to disk
      sizeThresholdBytes: 26214400  # 25 MB → disk
      latencyThresholdMs: 8000      # >8s download → disk
      readyDir: "data/ready"

# DHPO client tuning
dhpo:
  client:
    getNewEnabled: false
    searchDaysBack: 1000          # Fetch 1000 days (as per requirement)
    retriesOnMinus4: 3
    connectTimeoutMs: 10000
    readTimeoutMs: 30000
    downloadTimeoutMs: 180000
    stageToDiskThresholdMb: 25
    downloadConcurrency: 24       # High parallelism for SOAP
