spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/claims}          # e.g. jdbc:postgresql://db:5432/claims
    username: ${DB_USER:claims_user}
    password: ${DB_PASSWORD:securepass}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 8
      auto-commit: true
      connection-timeout: 15000
      validation-timeout: 5000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 200
      hibernate.order_inserts: true
      hibernate.order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  main:
    allow-bean-definition-overriding: false
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=20000,expireAfterAccess=30m,recordStats

logging:
  pattern:
    console: "%d{ISO8601} %-5level [%thread] %logger{36} - %msg%n"
  level:
    com.acme.claims: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.ws.client: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,threaddump,env,loggers"
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# ================== CLAIMS APP ==================
claims:
  ingestion:
    # SOAP profile in prod – IngestionConfig ensures only a single fetcher/acker is active
    profile: soap
    localfs:
      archive-fail-dir: ./data/archive/fail
      archive-ok-dir: ./data/archive/ok

    scheduler:
      fixedDelayString: "PT2M"            # poll every 2 minutes
      initialDelayString: "PT0S"

    # SOAP fetcher / acker config
    soap:
      endpoint: ${DHPO_SOAP_ENDPOINT}     # e.g. https://dhpo.example/soap
      username: ${DHPO_SOAP_USER}
      password: ${DHPO_SOAP_PASSWORD}
      connect-timeout-ms: 5000
      read-timeout-ms: 15000

    ack:
      enabled: true                       # best-effort after success (per requirements)

    executor:
      core-pool-size: 6
      max-pool-size: 12
      queue-capacity: 1000
    poll:
      fixedDelayMs: 1000   # 20s default

  parser:
    allowNonSchemaAttachments: false
    maxAttachmentBytes: 10485760
    failOnXsdError: true                  # stricter in prod


  # ===== Refdata & Bootstrap =====
  refdata:
    auto-insert: true
    bootstrap:
      enabled: true
      location: "classpath:refdata/"

# Optional: enable a real cache for ref lookups in prod (Caffeine)
claims.security.ame:
  enabled: true
  keystore:
    type: "PKCS12"
    path: "file:config/claims.p12"
    alias: "claims-ame"
    passwordEnv: "CLAIMS_AME_STORE_PASS"
  crypto:
    kekRotationAllowed: true
    gcmTagBits: 128
    keyId : claims-ame.v1

# Active SOAP client properties
claims.soap:
  endpoint: ${DHPO_SOAP_ENDPOINT}
  soap12: false
  connectTimeoutMs: 5000
  readTimeoutMs: 15000
  retry:
    maxAttempts: 3
    backoffMs: 500
  poll:
    fixedDelayMs: 1800000
  downloadConcurrency: 16

# DHPO client tuning
dhpo.client:
  getNewEnabled: false
  searchDaysBack: 100
  retriesOnMinus4: 3
  connectTimeoutMs: 6000
  readTimeoutMs: 15000
  downloadTimeoutMs: 120000
  stageToDiskThresholdMb: 25
