# src/main/resources/application.yml (excerpt)
#
# PRODUCTION OPTIMIZATION NOTES:
# The commented values below (# Production: ...) represent optimized settings for production deployment.
# These can be uncommented when deploying to EC2 for better performance.
# Current values are set for development/testing environment.
#
# TODO: Merge all YML configurations into a single application.yml file
# - Combine application.yml, application-soap.yml, application-ingestion.yml, etc.
# - Remove duplicate properties and consolidate configurations
spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16

claims:
  ingestion:
    concurrency:
      parserWorkers: 16       # Original: 16 workers for parallel processing
      # parserWorkers: 32     # Production: Increased for production: more parallel processing
    queue:
      capacity: 512           # Original: 512 capacity for burst handling
      # capacity: 1024       # Production: Increased for production: larger queue for burst handling
    poll:
      fixedDelayMs: 1000      # Original: 1000ms polling delay
      # fixedDelayMs: 500    # Production: Faster polling for production responsiveness
  soap:
    downloadConcurrency: 16   # Original: 16 concurrent downloads
    # downloadConcurrency: 32 # Production: Increased for production: match worker threads
    transport: http
    endpoint: "https://dhpo.eclaimlink.ae/validateTransactions.asmx"
    # SOAP 1.1 default (SOAPAction is set). Keep switch if you ever need 1.2 later.
    soap12: false
    connectTimeoutMs: 15000   # Original: 15000ms connection timeout
    # connectTimeoutMs: 10000 # Production: Faster timeout for production
    readTimeoutMs: 120000     # Original: 120000ms read timeout for large files
    # readTimeoutMs: 60000    # Production: Optimized for typical file sizes
    retry:
      maxAttempts: 3          # Original: 3 retry attempts
      # maxAttempts: 3        # Production: Standard retry policy (same)
      backoffMs: 500          # Original: 500ms backoff delay
      # backoffMs: 1000       # Production: Faster backoff for production
    poll:
      fixedDelayMs: 1800000    # 30 min between delta polls per facility
  fetch:
    stageToDisk:
      force: false          # global override
      sizeThresholdBytes: 26214400  # 25 MB → disk
      latencyThresholdMs: 8000      # >8s download → disk
      readyDir: "data/ready"

# env defaults (may be overridden by DB per facility)
#DHPO_DEFAULT_LOGIN: "env-user"
#DHPO_DEFAULT_PWD: "env-pass"

dhpo:
  client:
    getNewEnabled: false
    searchDaysBack: 100
    retriesOnMinus4: 3
    connectTimeoutMs: 6000    # Original: 6000ms connection timeout
    # connectTimeoutMs: 6000  # Production: Standard timeout for production (same)
    readTimeoutMs: 15000      # Original: 15000ms read timeout
    # readTimeoutMs: 15000    # Production: Optimized for production (same)
    downloadTimeoutMs: 120000 # Original: 120000ms download timeout
    # downloadTimeoutMs: 60000 # Production: Optimized for typical file sizes
    stageToDiskThresholdMb: 25

claims.security.ame:
  enabled: true
  keystore:
    type: "PKCS12"                    # or "PKCS12" or "FILE"
    path: "file:config/claims.p12" # or "file:config/claims.p12" or "file:config/ame.key"
    alias: "claims-ame"
    passwordEnv: "CLAIMS_AME_STORE_PASS"   # only store/pass are env-based
  crypto:
    kekRotationAllowed: true
    gcmTagBits: 128
    keyId : claims-ame.v1 #  used in enc_meta to mark which key encrypted the row
